apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid
  template:
    metadata:
      labels:
        app: bid
    spec:
      containers:
        - name: bid
          image: jarrodm1234/auction-website-bid
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: BID_MYSQL_URI
              value: 'mysql://bid-mysql-srv:8080/bid'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: auction
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: bid-srv
spec:
  selector:
    app: bid
  ports:
    - name: bid
      protocol: TCP
      port: 3000
      targetPort: 3000
